name = "NekosLife"
author = "Nekos"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5e9bba2f63307628da29aeea107b4d2f913abc24e433c00d5af1cd87b346e50"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
