name = "NekosLife"
author = "Nekos"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c74c8ea95f232ad4f87c125fcfafa6cab55cbbaa706becf706f6323a59f8c43"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
